const Date1 = new Date()
const date1 = Date1.getDate()
const month = Date1.getMonth()
const year = Date1.getFullYear()
const hours = Date1.getHours()
const minutes = Date1.getMinutes()
const seconds = Date1.getSeconds()
const milliseconds = Date1.getMilliseconds()
const time = Date1.getTime()
const day = Date1.getDay()
const UTCDate1 = Date1.getUTCDate()
const UTCFullYear = Date1.getUTCFullYear()   
const UTCHours = Date1.getUTCHours()
const UTCMinutes = Date1.getUTCMinutes()
const UTCSeconds = Date1.getUTCSeconds()
const UTCMilliseconds = Date1.getUTCMilliseconds()
const UTCDay = Date1.getUTCDay()
const UTCMonth = Date1.getUTCMonth()
const toDate1String = Date1.toDateString()
const toISOString = Date1.toISOString()
const toJSON = Date1.toJSON()
const toLocaleDate1String = Date1.toLocaleDateString()
const toLocaleString = Date1.toLocaleString()
const toLocaleTimeString = Date1.toLocaleTimeString()
const toString = Date1.toString()
const toTimeString = Date1.toTimeString()
const toUTCString = Date1.toUTCString()

module.exports = {
    date1, month, year, hours, minutes, seconds, milliseconds, time, day, UTCDate1, UTCFullYear, UTCHours, UTCMinutes, UTCSeconds, UTCMilliseconds, UTCDay, UTCMonth, toDate1String, toISOString, toJSON, toLocaleDate1String, toLocaleString, toLocaleTimeString, toString, toTimeString, toUTCString
}